# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Default'   # Nom de ton agent pool

steps:
- powershell: Write-Host "Hello World depuis mon Windows 11"
  displayName: 'Hello depuis agent local'
