<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QMTGroup.Camera\QMTGroup.Camera.csproj" />
    <ProjectReference Include="..\QMTGroup.Core\QMTGroup.Core.csproj" />
    <ProjectReference Include="..\QMTGroup.DSL.Library\QMTGroup.DSL.Library.csproj" />
    <ProjectReference Include="..\QMTGroup.DSL.Lua\QMTGroup.DSL.Lua.csproj" />
  </ItemGroup>

</Project>
